/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataRouteImport } from './routes/data'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCheckoutOrderIdRouteImport } from './routes/_authenticated/checkout/$orderId'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedAdminAnalyticsIndexRouteImport } from './routes/_authenticated/admin/analytics/index'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin/categories/index'
import { Route as AuthenticatedAdminCustomersIndexRouteImport } from './routes/_authenticated/admin/customers/index'
import { Route as AuthenticatedAdminNotificationsIndexRouteImport } from './routes/_authenticated/admin/notifications/index'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin/orders/index'
import { Route as AuthenticatedAdminPaymentsIndexRouteImport } from './routes/_authenticated/admin/payments/index'
import { Route as AuthenticatedAdminPricingTemplatesIndexRouteImport } from './routes/_authenticated/admin/pricing-templates/index'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products/index'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin/products/new'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminSupportIndexRouteImport } from './routes/_authenticated/admin/support/index'
import { Route as AuthenticatedAdminTransactionsIndexRouteImport } from './routes/_authenticated/admin/transactions/index'
import { Route as AuthenticatedAdminWalletIndexRouteImport } from './routes/_authenticated/admin/wallet/index'
import { Route as AuthenticatedAdminProductsProductIdEditRouteImport } from './routes/_authenticated/admin/products/$productId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCheckoutOrderIdRoute =
  AuthenticatedCheckoutOrderIdRouteImport.update({
    id: '/checkout/$orderId',
    path: '/checkout/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsIndexRoute =
  AuthenticatedAdminAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersIndexRoute =
  AuthenticatedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsIndexRoute =
  AuthenticatedAdminNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsIndexRoute =
  AuthenticatedAdminPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPricingTemplatesIndexRoute =
  AuthenticatedAdminPricingTemplatesIndexRouteImport.update({
    id: '/pricing-templates/',
    path: '/pricing-templates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportIndexRoute =
  AuthenticatedAdminSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsIndexRoute =
  AuthenticatedAdminTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWalletIndexRoute =
  AuthenticatedAdminWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsProductIdEditRoute =
  AuthenticatedAdminProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/payments/': typeof AuthenticatedAdminPaymentsIndexRoute
  '/admin/pricing-templates/': typeof AuthenticatedAdminPricingTemplatesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/admin/transactions/': typeof AuthenticatedAdminTransactionsIndexRoute
  '/admin/wallet/': typeof AuthenticatedAdminWalletIndexRoute
  '/admin/products/$productId/edit': typeof AuthenticatedAdminProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersIndexRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsIndexRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsIndexRoute
  '/admin/pricing-templates': typeof AuthenticatedAdminPricingTemplatesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/support': typeof AuthenticatedAdminSupportIndexRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsIndexRoute
  '/admin/wallet': typeof AuthenticatedAdminWalletIndexRoute
  '/admin/products/$productId/edit': typeof AuthenticatedAdminProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/checkout/$orderId': typeof AuthenticatedCheckoutOrderIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/_authenticated/admin/analytics/': typeof AuthenticatedAdminAnalyticsIndexRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/customers/': typeof AuthenticatedAdminCustomersIndexRoute
  '/_authenticated/admin/notifications/': typeof AuthenticatedAdminNotificationsIndexRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/payments/': typeof AuthenticatedAdminPaymentsIndexRoute
  '/_authenticated/admin/pricing-templates/': typeof AuthenticatedAdminPricingTemplatesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/_authenticated/admin/transactions/': typeof AuthenticatedAdminTransactionsIndexRoute
  '/_authenticated/admin/wallet/': typeof AuthenticatedAdminWalletIndexRoute
  '/_authenticated/admin/products/$productId/edit': typeof AuthenticatedAdminProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data'
    | '/support'
    | '/admin'
    | '/dashboard'
    | '/products/$slug'
    | '/products/'
    | '/checkout/$orderId'
    | '/orders/$orderId'
    | '/admin/'
    | '/orders/'
    | '/admin/products/new'
    | '/admin/analytics/'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/notifications/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/pricing-templates/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/support/'
    | '/admin/transactions/'
    | '/admin/wallet/'
    | '/admin/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data'
    | '/support'
    | '/dashboard'
    | '/products/$slug'
    | '/products'
    | '/checkout/$orderId'
    | '/orders/$orderId'
    | '/admin'
    | '/orders'
    | '/admin/products/new'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing-templates'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/wallet'
    | '/admin/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data'
    | '/support'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/checkout/$orderId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/admin/'
    | '/_authenticated/orders/'
    | '/_authenticated/admin/products/new'
    | '/_authenticated/admin/analytics/'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/customers/'
    | '/_authenticated/admin/notifications/'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/payments/'
    | '/_authenticated/admin/pricing-templates/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/support/'
    | '/_authenticated/admin/transactions/'
    | '/_authenticated/admin/wallet/'
    | '/_authenticated/admin/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataRoute: typeof DataRoute
  SupportRoute: typeof SupportRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/checkout/$orderId': {
      id: '/_authenticated/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof AuthenticatedCheckoutOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics/': {
      id: '/_authenticated/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers/': {
      id: '/_authenticated/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications/': {
      id: '/_authenticated/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments/': {
      id: '/_authenticated/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pricing-templates/': {
      id: '/_authenticated/admin/pricing-templates/'
      path: '/pricing-templates'
      fullPath: '/admin/pricing-templates/'
      preLoaderRoute: typeof AuthenticatedAdminPricingTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support/': {
      id: '/_authenticated/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AuthenticatedAdminSupportIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transactions/': {
      id: '/_authenticated/admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wallet/': {
      id: '/_authenticated/admin/wallet/'
      path: '/wallet'
      fullPath: '/admin/wallet/'
      preLoaderRoute: typeof AuthenticatedAdminWalletIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/$productId/edit': {
      id: '/_authenticated/admin/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/admin/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedAdminProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
  AuthenticatedAdminAnalyticsIndexRoute: typeof AuthenticatedAdminAnalyticsIndexRoute
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
  AuthenticatedAdminCustomersIndexRoute: typeof AuthenticatedAdminCustomersIndexRoute
  AuthenticatedAdminNotificationsIndexRoute: typeof AuthenticatedAdminNotificationsIndexRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
  AuthenticatedAdminPaymentsIndexRoute: typeof AuthenticatedAdminPaymentsIndexRoute
  AuthenticatedAdminPricingTemplatesIndexRoute: typeof AuthenticatedAdminPricingTemplatesIndexRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminSupportIndexRoute: typeof AuthenticatedAdminSupportIndexRoute
  AuthenticatedAdminTransactionsIndexRoute: typeof AuthenticatedAdminTransactionsIndexRoute
  AuthenticatedAdminWalletIndexRoute: typeof AuthenticatedAdminWalletIndexRoute
  AuthenticatedAdminProductsProductIdEditRoute: typeof AuthenticatedAdminProductsProductIdEditRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
    AuthenticatedAdminAnalyticsIndexRoute:
      AuthenticatedAdminAnalyticsIndexRoute,
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
    AuthenticatedAdminCustomersIndexRoute:
      AuthenticatedAdminCustomersIndexRoute,
    AuthenticatedAdminNotificationsIndexRoute:
      AuthenticatedAdminNotificationsIndexRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
    AuthenticatedAdminPaymentsIndexRoute: AuthenticatedAdminPaymentsIndexRoute,
    AuthenticatedAdminPricingTemplatesIndexRoute:
      AuthenticatedAdminPricingTemplatesIndexRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminSupportIndexRoute: AuthenticatedAdminSupportIndexRoute,
    AuthenticatedAdminTransactionsIndexRoute:
      AuthenticatedAdminTransactionsIndexRoute,
    AuthenticatedAdminWalletIndexRoute: AuthenticatedAdminWalletIndexRoute,
    AuthenticatedAdminProductsProductIdEditRoute:
      AuthenticatedAdminProductsProductIdEditRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCheckoutOrderIdRoute: typeof AuthenticatedCheckoutOrderIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCheckoutOrderIdRoute: AuthenticatedCheckoutOrderIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataRoute: DataRoute,
  SupportRoute: SupportRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
